# Generated by Django 3.0.7 on 2020-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa_classroom',
            name='classroom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarefa_classroom',
            name='data_limite',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tarefa_classroom',
            name='descricao',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='tarefa_classroom',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarefa_classroom',
            name='materia',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tarefa_classroom',
            name='titulo',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tarefa_personalizada',
            name='classroom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarefa_personalizada',
            name='data_limite',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tarefa_personalizada',
            name='descricao',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='tarefa_personalizada',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarefa_personalizada',
            name='materia',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tarefa_personalizada',
            name='titulo',
            field=models.CharField(max_length=400),
        ),
    ]
