# Generated by Django 3.0.7 on 2020-08-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200807_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa_classroom',
            old_name='descricao',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='tarefa_personalizada',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
