# Generated by Django 3.0.7 on 2020-08-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200807_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa_classroom',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='tarefa_personalizada',
            name='classroom',
        ),
        migrations.AddField(
            model_name='tarefa_classroom',
            name='done',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='tarefa_personalizada',
            name='done',
            field=models.CharField(default='false', max_length=50),
        ),
    ]
