# Generated by Django 3.0.7 on 2020-08-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20200808_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa_classroom',
            name='classroom',
            field=models.CharField(default='true', max_length=50),
        ),
        migrations.AddField(
            model_name='tarefa_personalizada',
            name='classroom',
            field=models.CharField(default='false', max_length=50),
        ),
    ]
