# Generated by Django 3.0.7 on 2020-08-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200808_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tarefa_classroom',
            name='descrição',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarefa_personalizada',
            name='descrição',
            field=models.TextField(),
        ),
    ]
